
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import content from "../data/trip-content.json";

type Event = { time:string; area:string; title:string; description:string; map:string; transport:string; duration:string; cost:string; booking:string; photo:string; food:string; luggage:string; clothes:string; planB:string; safety:string };
type Day = { iso:string; shortDate:string; weekday:string; title:string; city:string; day:number; route:string; hardTime:string; weather:string; budget:string; food:string; luggage:string; clothes:string; planB:string; events:Event[] };
type Vlog = (typeof content.vlog)[number];
type Tab = "today" | "days" | "tickets" | "budget" | "vlog";
type IconName = "today"|"days"|"ticket"|"budget"|"vlog"|"train"|"walk"|"food"|"place"|"camera"|"map"|"chevron"|"hotel";

const days = content.days as Day[];

const themes = [
  {match:"Interlaken",key:"interlaken",flag:"🇨🇭",code:"INT",coord:"46.6863° N · 7.8632° E"}, {match:"Lauterbrunnen",key:"lauterbrunnen",flag:"🇨🇭",code:"LBR",coord:"46.5935° N · 7.9091° E"},

  {match:"Zermatt",key:"zermatt",flag:"🇨🇭",code:"ZMT",coord:"46.0207° N · 7.7491° E"}, {match:"米兰",key:"milan",flag:"🇮🇹",code:"MIL",coord:"45.4642° N · 9.1900° E"},
  {match:"威尼斯",key:"venice",flag:"🇮🇹",code:"VCE",coord:"45.4408° N · 12.3155° E"}, {match:"佛罗伦萨",key:"florence",flag:"🇮🇹",code:"FLR",coord:"43.7696° N · 11.2558° E"},
  {match:"罗马",key:"rome",flag:"🇮🇹",code:"ROM",coord:"41.9028° N · 12.4964° E"},
];

function CityArt({kind}:{kind:string}){
  if(kind==="milan")return <svg className="hero-landscape city-art" viewBox="0 0 560 230" preserveAspectRatio="none" aria-hidden><path d="M80 202h400M145 202v-67h46v67m178 0v-67h46v67M205 202V91h150v111M230 91l15-35 13 35m44 0 13-35 15 35M275 91V39l5-18 5 18v52M220 127h120M247 202v-51h66v51"/><path className="route-line" d="M55 211h450"/></svg>;
  if(kind==="venice")return <svg className="hero-landscape city-art" viewBox="0 0 560 230" preserveAspectRatio="none" aria-hidden><path d="M55 174h450M108 174c42-85 100-85 142 0m0 0c42-85 100-85 142 0M80 196c85-13 132 13 210 0s132 13 205 0M92 211c72-11 120 11 186 0s126 11 196 0"/><path d="M248 174v-73h64v73m-50-73V72h36v29m-18-29V45"/></svg>;
  if(kind==="florence")return <svg className="hero-landscape city-art" viewBox="0 0 560 230" preserveAspectRatio="none" aria-hidden><path d="M55 205h450M165 205v-73h58v73m114 0v-73h58v73M218 205v-76c0-63 124-63 124 0v76M235 112c16-58 74-58 90 0M280 68V35M268 46h24M247 205v-58h66v58"/></svg>;
  if(kind==="rome")return <svg className="hero-landscape city-art" viewBox="0 0 560 230" preserveAspectRatio="none" aria-hidden><path d="M70 202h420M112 202v-94c0-22 336-22 336 0v94M112 126h336M112 157h336M141 126v-21m47 21v-25m47 25V98m47 28V97m47 29V99m47 27v-23m47 23v-18"/>{[145,200,255,310,365,420].map(x=><path key={x} d={`M${x-13} 202v-24c0-22 26-22 26 0v24`}/>)}</svg>;
  if(kind==="zermatt")return <svg className="hero-landscape city-art" viewBox="0 0 560 230" preserveAspectRatio="none" aria-hidden><path d="M20 205 150 159l52 20L304 30l38 87 32-19 166 107M304 30l-20 81 41-32 17 38M190 182l45-40 27 25"/><path className="route-line" d="M54 211 C180 180 260 215 505 186"/></svg>;
  return <svg className="hero-landscape city-art" viewBox="0 0 560 230" preserveAspectRatio="none" aria-hidden><path d="M0 190 80 105l61 57 64-95 86 113 69-84 83 72 117-80v142H0Z" className="mountain-back"/><path d="M0 207 102 148l57 42 73-75 86 93 70-61 69 52 103-29v60H0Z" className="mountain-front"/><path className="route-line" d="M42 194 C128 116 188 207 274 139 S420 104 518 166"/><circle cx="42" cy="194" r="4"/><circle cx="274" cy="139" r="4"/><circle cx="518" cy="166" r="4"/></svg>;
}

function Icon({name,size=18}:{name:IconName;size?:number}) {

  const paths:Record<IconName,React.ReactNode>={
    today:<><circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/></>, days:<><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/></>,
    ticket:<><path d="M4 7a2 2 0 0 0 2-2h12a2 2 0 0 0 2 2v2a3 3 0 0 0 0 6v2a2 2 0 0 0-2 2H6a2 2 0 0 0-2-2v-2a3 3 0 0 0 0-6Z"/><path d="M12 7v2M12 15v2"/></>,
    budget:<><rect x="3" y="6" width="18" height="13" rx="3"/><path d="M16 12h5M7 6V4h10"/></>, vlog:<><rect x="3" y="6" width="14" height="12" rx="2"/><path d="m17 10 4-2v8l-4-2Z"/></>,
    train:<><rect x="5" y="3" width="14" height="15" rx="4"/><path d="M8 21l2-3M16 18l2 3M8 8h8M8 13h.01M16 13h.01"/></>, walk:<><circle cx="12" cy="4" r="2"/><path d="m10 22 1-7-3-3 2-5 4 3 3 1M14 22l-3-7"/></>, hotel:<><path d="M4 20V5h16v15M8 9h2M14 9h2M8 13h2M14 13h2M9 20v-3h6v3"/></>,
    food:<><path d="M7 3v8M4 3v5a3 3 0 0 0 6 0V3M7 11v10M16 3v18M16 3c4 2 4 8 0 10"/></>, place:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>, camera:<><path d="M5 7h3l2-2h4l2 2h3a2 2 0 0 1 2 2v9H3V9a2 2 0 0 1 2-2Z"/><circle cx="12" cy="13" r="3"/></>, map:<><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3Z"/><path d="M9 3v15M15 6v15"/></>, chevron:<path d="m9 18 6-6-6-6"/>,
  };
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>;
}

function openMap(query:string) { if(query) window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`,"_blank","noopener,noreferrer"); }
function eventKind(e:Event):IconName { const s=`${e.title}${e.area}${e.transport}${e.food}${e.photo}`; if(/入住|酒店|民宿|住宿|BASE/i.test(s))return"hotel"; if(/餐|吃|午餐|晚餐|咖啡|补给|Coop/i.test(s))return"food"; if(/拍|Vlog|口播|镜头/i.test(s))return"camera"; if(/火车|列车|SBB|车站|机场|航班|船|巴士|交通|出发|抵达|高铁/i.test(s))return"train"; if(/步行|徒步|逛|散步/i.test(s))return"walk"; return"place"; }
function statusPills(e:Event){ const out:string[]=[]; const s=`${e.booking} ${e.cost} ${e.planB} ${e.safety}`; if(/已购|已付/.test(s))out.push("已购"); if(/免费|CHF0|€0/.test(s))out.push("免费"); if(/预约|提前|必须/.test(s))out.push("需预约"); if(/天气|雨|风|取消|关闭/.test(s))out.push("天气敏感"); if(/Plan B|雨天|替代/.test(s))out.push("雨天替代"); return [...new Set(out)].slice(0,3); }
function cleanNode(s:string){return s.replace(/\([^)]*\)|（[^）]*）/g,"").trim();}
function routeNodes(day:Day){ const raw=day.route.split(/→|➜|—|\+|\/|｜/).map(cleanNode).filter(Boolean); return raw.slice(0,6); }

function matchVlog(e:Event):Vlog|undefined { const hay=`${e.title} ${e.area} ${e.map}`.toLowerCase(); return content.vlog.find(v=>{const loc=v.location.toLowerCase(); return loc.length>1&&(hay.includes(loc)||loc.includes(e.area.toLowerCase())||hay.includes(loc.split(/[（(·]/)[0]));}); }
function money(currency:string,value:string){const n=Number(value);if(!Number.isFinite(n))return `${currency} ${value}`;const symbol=currency==="CNY"?"¥":currency==="EUR"?"€":currency==="CHF"?"CHF ":`${currency} `;return `${symbol}${n.toLocaleString("zh-CN",{minimumFractionDigits:n%1?2:0,maximumFractionDigits:2})}`;}
function budgetCategory(name:string){if(/酒店|住宿/.test(name))return"住宿";if(/票|Pass|Duomo|Basilica|Palace|Museum|Colosseo|跳伞|观景|缆车/i.test(name))return"门票";if(/餐|吃|咖啡|补给/.test(name))return"餐饮";if(/备用|应急|机动/.test(name))return"备用金";return"交通";}
function ticketTone(name:string){if(/skydive|跳伞/i.test(name))return"sky";if(/Duomo|Milan/i.test(name))return"milan";if(/Venez|Mark|Doge/i.test(name))return"venice";if(/Train|→|Pass|rail|Firenze|Roma/i.test(name))return"rail";return"stone";}
function zurichNow(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Zurich",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date());const get=(t:string)=>parts.find(p=>p.type===t)?.value||"";return{date:`${get("year")}-${get("month")}-${get("day")}`,minutes:Number(get("hour"))*60+Number(get("minute"))};}
function initialDay(){const i=days.findIndex(d=>d.iso===zurichNow().date);return i>=0?i:0;}
function eventStart(time:string){const m=time.match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):Number.MAX_SAFE_INTEGER;}
type LocalState="done"|"shot"|"skip";
function Status({value}:{value:string}) { const kind=/已购|已付/.test(value)?"done":/待确认|待定/.test(value)?"check":"pending"; return <span className={`status ${kind}`}>{value}</span>; }

export default function Home(){
  const [dayIndex,setDayIndex]=useState(initialDay),[tab,setTab]=useState<Tab>("today"),[vlogOpen,setVlogOpen]=useState(0); const [spotVlog,setSpotVlog]=useState<Vlog|null>(null);
  const [prompter,setPrompter]=useState<{title:string;short:string;long:string;mode:"short"|"long"}|null>(null);
  const [eventStates,setEventStates]=useState<Record<string,LocalState>>({});
  const day=days[dayIndex]; const theme=themes.find(t=>day.city.includes(t.match)||day.title.includes(t.match))||themes[dayIndex<4?0:3];

  const dayTickets=useMemo(()=>content.tickets.filter(t=>t.date===day.shortDate||t.date.includes(day.shortDate)),[day.shortDate]);
  const nav:[Tab,string,IconName][]=[["today","今日","today"],["days","行程","days"],["tickets","票务","ticket"],["budget","预算","budget"],["vlog","Vlog","vlog"]];
  const categoryTotals=useMemo(()=>{const rates:Record<string,number>={CNY:1,CHF:9,EUR:8.4};const sums:Record<string,number>={交通:0,住宿:0,门票:0,餐饮:0,备用金:0};content.budget.forEach(b=>sums[budgetCategory(b.name)]+=(Number(b.high)||0)*(rates[b.currency]||1));const total=Object.values(sums).reduce((a,b)=>a+b,0)||1;return Object.entries(sums).map(([name,value])=>({name,value,pct:Math.round(value/total*100)}));},[]);
  const localNow=zurichNow(); const isTravelDay=days.some(d=>d.iso===localNow.date); const eventCursor=day.events.findIndex(e=>eventStart(e.time)>localNow.minutes); const nowIndex=isTravelDay&&day.iso===localNow.date?Math.max(0,eventCursor-1):0; const nextIndex=isTravelDay&&day.iso===localNow.date?(eventCursor<0?day.events.length-1:eventCursor):Math.min(1,day.events.length-1);
  useEffect(()=>{try{setEventStates(JSON.parse(localStorage.getItem("trip-execution-v1")||"{}"));}catch{}},[]);
  function setExecution(index:number,state:LocalState){const key=`${day.iso}:${index}`;const next={...eventStates,[key]:state};setEventStates(next);localStorage.setItem("trip-execution-v1",JSON.stringify(next));}
  return <main className={`app-shell theme-${theme.key} tab-${tab}`}>
    {tab==="today"&&<>
      <section className="hero-card"><CityArt kind={theme.key}/><div className="hero-content"><div className="hero-top"><div><p className="day-kicker">{theme.flag} DAY {day.day} / {days.length} · {day.shortDate} {day.weekday}</p><h2>{day.title}</h2><p className="hero-city">{theme.code} · {day.city}</p></div><span className="hero-coord">{theme.coord}</span></div><div className="hero-journey">{routeNodes(day).slice(0,3).join(" → ")}</div><div className="hero-foot"><span>{day.weather}</span><span>{day.budget}</span></div></div></section>
      <div className="day-strip" aria-label="旅行进度">{days.map((d,i)=>{const th=themes.find(t=>d.city.includes(t.match)||d.title.includes(t.match))||themes[i<4?0:3];return <button key={d.iso} className={i===dayIndex?"active":""} onClick={()=>setDayIndex(i)}><small>{th.flag} DAY {i+1}</small><b>{d.shortDate}</b><span>{th.code}</span></button>})}</div>
      <section className="now-next"><div className="mode-label">{isTravelDay&&day.iso===localNow.date?"LIVE · 当地时间":"手动预览"}</div><article><span>NOW</span><time>{day.events[nowIndex]?.time}</time><div><b>{day.events[nowIndex]?.title}</b><small>{day.events[nowIndex]?.area}</small></div></article><article><span>NEXT</span><time>{day.events[nextIndex]?.time}</time><div><b>{day.events[nextIndex]?.title}</b><small>{day.events[nextIndex]?.transport||day.events[nextIndex]?.area}</small></div></article></section>
      <section className="route-ribbon"><div className="route-head"><span><Icon name="map" size={15}/> 今日路线</span><button onClick={()=>openMap(day.city)}>完整地图 ↗</button></div><div className="route-nodes">{routeNodes(day).map((n,i)=><div key={`${n}-${i}`}><i>{i+1}</i><span>{n}</span></div>)}</div></section>
      <section className="section-block timeline-section"><div className="section-heading"><h3>今天怎么走</h3><span>硬时间：{day.hardTime||"无固定预约"}</span></div><div className="timeline">{day.events.map((e,index)=>{const kind=eventKind(e),v=matchVlog(e),pills=statusPills(e),state=eventStates[`${day.iso}:${index}`];return <article className={`timeline-item kind-${kind} ${state?`is-${state}`:""}`} key={`${e.time}-${index}`}><time>{e.time}</time><div className="rail"><i><Icon name={kind} size={14}/></i></div><div className="event-card"><div className="event-top"><span className="tag">{e.area}</span>{v&&<button className="vlog-chip" onClick={()=>setSpotVlog(v)}><Icon name="camera" size={15}/>口播</button>}</div><strong>{e.title}</strong><small>{e.transport}{e.duration?` · ${e.duration}`:""}</small><div className="pills">{pills.map(p=><span key={p}>{p}</span>)}{v&&<span className="vlog">Vlog重点</span>}</div><div className="quick-meta"><span>{e.cost||"费用待定"}</span><span>{e.booking||"无票务"}</span></div><div className="card-actions">{e.map&&<button onClick={()=>openMap(e.map)}><Icon name="map" size={17}/>Google Maps</button>}</div><details><summary>安全、Plan B 与详细说明</summary><p>{e.description}</p>{e.safety&&<p><b>注意：</b>{e.safety}</p>}{e.planB&&<p><b>变化方案：</b>{e.planB}</p>}{e.photo&&<p><b>拍摄：</b>{e.photo}</p>}</details><div className="execution-actions" aria-label="本地执行状态"><button className={state==="done"?"active":""} onClick={()=>setExecution(index,"done")}>✓ 完成</button><button className={state==="shot"?"active":""} onClick={()=>setExecution(index,"shot")}>📷 已拍</button><button className={state==="skip"?"active":""} onClick={()=>setExecution(index,"skip")}>跳过</button></div></div></article>})}</div></section>
      {dayTickets.length>0&&<section className="section-block"><div className="section-heading"><h3>当天票务</h3><span>状态以文档为准</span></div><div className="stack-list">{dayTickets.map((t,i)=><article key={i}><Icon name="ticket"/><div><strong>{t.name}</strong><small>{t.time} · {t.price}</small></div><Status value={t.status}/></article>)}</div></section>}
      <section className="section-block"><div className="section-heading"><h3>现场提示</h3><span>按需展开查看</span></div><div className="notes-grid">{[["吃饭补给",day.food,"food"],["行李",day.luggage,"ticket"],["穿搭",day.clothes,"today"],["Plan B",day.planB,"map"]].map(([a,b,c])=><details key={a}><summary><Icon name={c as IconName}/><span>{a}</span></summary><p>{b}</p></details>)}</div></section>

    </>}
    {tab==="days"&&<section className="page-section journal-page"><div className="page-title"><p>ROUTE BOOK</p><h2>行程</h2><span>从阿尔卑斯到古罗马的九日章节</span></div><TripChapter title="CHAPTER 01 · 瑞士" subtitle="9/27 — 9/30 · 高山与冰川" items={days.slice(0,4)} offset={0} open={i=>{setDayIndex(i);setTab("today")}}/><div className="border-crossing"><span>跨境</span><b>Zermatt → Milano</b><small>雪山冷色在这里转入意大利暖色</small></div><TripChapter title="CHAPTER 02 · 意大利" subtitle="9/30 — 10/5 · 建筑与古城" items={days.slice(4)} offset={4} open={i=>{setDayIndex(i);setTab("today")}}/></section>}
    {tab==="tickets"&&<section className="page-section wallet-page"><div className="page-title"><p>WALLET</p><h2>票务</h2><span>购买状态与使用日期，一眼确认</span></div><div className="ticket-list">{content.tickets.map((t,i)=><article className={`wallet-card tone-${ticketTone(t.name)}`} key={i}><div className="ticket-stub"><Icon name="ticket" size={20}/><b>{t.date}</b><small>{t.time||"全天"}</small></div><div className="ticket-main"><small>TRAVEL PASS · {String(i+1).padStart(2,"0")}</small><strong>{t.name}</strong><p>{t.price}</p>{t.url&&<a href={t.url} target="_blank" rel="noreferrer">查看官方页面 ↗</a>}<Status value={t.status}/></div></article>)}</div></section>}
    {tab==="budget"&&<section className="page-section"><div className="page-title budget-hero"><p>MONEY DASHBOARD</p><h2>预算</h2><strong>{content.budgetSummary.recommended}</strong><div className="paid-split"><span>已确认</span><b>{content.budgetSummary.confirmed}</b></div><div className="budget-progress"><i style={{width:"58%"}}/></div></div><div className="category-chart">{categoryTotals.map((c,i)=><article key={c.name}><div className="donut" style={{"--pct":`${c.pct*3.6}deg`,"--i":i} as React.CSSProperties}><b>{c.pct}%</b></div><span>{c.name}</span></article>)}</div><div className="budget-summary"><article><span>基础预算</span><strong>{content.budgetSummary.base}</strong></article><article><span>汇率口径</span><strong>{content.budgetSummary.rates}</strong></article></div><div className="budget-list">{content.budget.map((b,i)=><article key={i}><div><strong>{b.name}</strong><small>{b.note}</small></div><div><b>{money(b.currency,b.low)}{b.high&&b.high!==b.low?` — ${money(b.currency,b.high)}`:""}</b><Status value={b.payment||"未付"}/></div></article>)}</div></section>}
    {tab==="vlog"&&<section className="page-section director-page"><div className="page-title"><p>DIRECTOR'S FIELD BOOK</p><h2>Vlog</h2><span>先说、再拍，背景资料最后看</span></div><div className="vlog-list">{content.vlog.map((v,i)=><article key={i} className={vlogOpen===i?"open":""}><button onClick={()=>setVlogOpen(vlogOpen===i?-1:i)}><span>{v.group}</span><strong>{v.location}</strong><b>{vlogOpen===i?"−":"+"}</b></button>{vlogOpen===i&&<VlogBody vlog={v} onPrompt={()=>setPrompter({title:v.location,short:v.script10,long:v.script30,mode:"short"})}/>}</article>)}</div></section>}
    {spotVlog&&<div className="modal-backdrop" onClick={()=>setSpotVlog(null)}><section className="vlog-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSpotVlog(null)}>×</button><p className="eyebrow">🎥 现场口播</p><h2>{spotVlog.location}</h2><VlogBody vlog={spotVlog} onPrompt={()=>setPrompter({title:spotVlog.location,short:spotVlog.script10,long:spotVlog.script30,mode:"short"})}/></section></div>}
    {prompter&&<Prompter data={prompter} update={setPrompter} close={()=>setPrompter(null)}/>} 
    <nav className="bottom-nav" aria-label="主导航">{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><i><Icon name={icon}/></i><span>{label}</span></button>)}</nav>
  </main>;
}

function TripChapter({title,subtitle,items,offset,open}:{title:string;subtitle:string;items:Day[];offset:number;open:(i:number)=>void}){return <section className="trip-chapter"><header><p>{title}</p><h3>{subtitle}</h3></header><div>{items.map((d,j)=><button key={d.iso} onClick={()=>open(offset+j)}><span className="chapter-day">D{offset+j+1}</span><div><small>{d.shortDate} · {d.city}</small><strong>{d.title}</strong><p>{routeNodes(d).slice(0,4).join(" → ")}</p></div><Icon name="chevron"/></button>)}</div></section>}
function VlogBody({vlog:v,onPrompt}:{vlog:Vlog;onPrompt?:()=>void}){return <div className="vlog-body"><section className="script-card primary"><h4>10秒口播</h4><p>{v.script10||"本地点暂无10秒口播"}</p>{v.script10&&onPrompt&&<button onClick={onPrompt}>进入提词模式</button>}</section>{v.script30&&<section className="script-card"><h4>30秒口播</h4><p>{v.script30}</p>{onPrompt&&<button onClick={onPrompt}>进入提词模式</button>}</section>}{v.shots.length>0&&<section className="shot-list"><h4>必拍镜头</h4>{v.shots.map((s,j)=><label key={j}><input type="checkbox"/ ><span>{s}</span></label>)}</section>}{v.changes.length>0&&<section className="change-note"><h4>现场变化</h4>{v.changes.map((s,j)=><p key={j}>{s}</p>)}</section>}{v.background&&<details><summary>背景速懂</summary><p>{v.background}</p></details>}{v.voiceover&&<details><summary>后期旁白</summary><p>{v.voiceover}</p></details>}{v.transition&&<details><summary>转场建议</summary><p>{v.transition}</p></details>}</div>}

function Prompter({data,update,close}:{data:{title:string;short:string;long:string;mode:"short"|"long"};update:React.Dispatch<React.SetStateAction<typeof data|null>>;close:()=>void}){const [size,setSize]=useState(34),[dark,setDark]=useState(true),[auto,setAuto]=useState(false);const scroller=useRef<HTMLDivElement>(null);useEffect(()=>{if(!auto)return;const id=setInterval(()=>scroller.current?.scrollBy({top:1,behavior:"auto"}),55);return()=>clearInterval(id)},[auto]);const text=data.mode==="long"&&data.long?data.long:data.short;return <div className={`prompter ${dark?"dark":"light"}`} ref={scroller}><div className="prompter-tools"><button onClick={close}>完成 ×</button><button onClick={()=>update(p=>p?{...p,mode:p.mode==="short"?"long":"short"}:p)}>{data.mode==="short"?"切到30秒":"切到10秒"}</button><button onClick={()=>setSize(s=>Math.max(24,s-3))}>A−</button><button onClick={()=>setSize(s=>Math.min(56,s+3))}>A+</button><button onClick={()=>setAuto(v=>!v)}>{auto?"停止滚动":"慢速滚动"}</button><button onClick={()=>setDark(v=>!v)}>{dark?"浅色":"黑底"}</button></div><small>TELEPROMPTER · {data.mode==="short"?"10 SEC":"30 SEC"} · {data.title}</small><p style={{fontSize:size}}>{text}</p></div>}